dasmeta/terraform-aws-modules

modules/aws-ssl-certificate/certificates.tf, modules/aws-ssl-certificate/output.tf, modules/aws-ssl-certificate/variables.tf
https://tutorbot.atlassian.net/browse/DMVP-18
=> AWS SSL Certificates

modules/aws-load-balancer-controller/logs-to-cloudwatch.tf, modules/aws-load-balancer-controller/terraform-aws-alb-cloudwatch-logs-json/variables.tf
https://tutorbot.atlassian.net/browse/DMVP-79
=> update fix ingress

modules/aws-iam-user/README.md
add new Case 5 with local pgp_key
=> fix readme

modules/aws-cloudfront-security-headers/main.tf, modules/aws-cloudfront-security-headers/variables.tf
added the ability to select a version Node.js
=> add new variable  runtime

modules/aws-cloudfront-security-headers/main.tf
=> Dmvp 97 add cloud front security headeers

modules/cognito-identity-pool-final/client.tf, modules/cognito-identity-pool-final/iam-policy.tf, modules/cognito-identity-pool-final/iam-role.tf, modules/cognito-identity-pool-final/identity-pool.tf, modules/cognito-identity-pool-final/roles-attachment.tf, modules/cognito-identity-pool-final/user-pool.tf, modules/cognito-identity-pool-final/variables.tf
We need to create cognito identity pool. 
This module creates a cognito user pool and and an identity pool with its iam-role and iam-policy and attaches them to the pool.
=> Cognito module

modules/route53-alerts-notify/requirements.tf
DMVP-180 decrease health check module required aws provided version
=> DMVP-180 decrease health check module required aws provided version

modules/cognito-user-pool/README.md, modules/cognito-user-pool/clients.tf, modules/cognito-user-pool/domain.tf, modules/cognito-user-pool/group.tf, modules/cognito-user-pool/pool.tf, modules/cognito-user-pool/variables.tf
Our cognito module created a simple cognito setup with default values. We needed a module which would be able to make a more complex setup.
Some new parts are added to this module due to which we can add other features to the cognito setup except the default ones.
=> Bigger cognito setup.

modules/budgets/main.tf, modules/budgets/outputs.tf, modules/budgets/variables.tf, modules/budgets/versions.tf
this  module can be useful in ticket DMVP-186
=> add new module  budgets

modules/cognito-identity/README.md, modules/cognito-identity/identity.tf, modules/cognito-identity/roles-attachment.tf, modules/cognito-identity/variables.tf, modules/cognito-user-pool/domain.tf, modules/cognito-user-pool/group.tf
This module creates AWS Cognito Identity Pool and with this module the process of creation pools will become much more simple.
=> Cognito Identity Pool module

modules/cognito-user-pool/pool.tf, modules/cognito-user-pool/variables.tf
There are some problems in Cognito module.  By this PR they'll be fixed.
=> Cognito module fixes

modules/cognito-identity/identity.tf, modules/cognito-identity/variables.tf
The module was considered to be complete, but when it is used in real tasks, some fixes are needed. So this PR is going to make the module really complete and usable.
=> Identity pool module fixes

modules/cloudwatch-alarm-notify/cloudwatch_alarm.tf
minor fixes in cloudwatch_alarm module
=> minor fixes in cloudwatch_alarm module

modules/cloudfront-ssl-hsts/README.md
DMVP-149 additional fixed in S3 origin readme
=> DMVP-149 additional fixed in S3 origin readme

modules/ssl-certificate/certificates.tf, modules/ssl-certificate/variables.tf
Have certificate module variable fixes
=> Have certificate module variable fixes

modules/aws-rds-postgres/main.tf, modules/aws-rds-postgres/security-group.tf, modules/aws-rds-postgres/variables.tf
Add count in security-group create and add public access
=> Add Variables in module

modules/mongodb-atlas/README.md, modules/mongodb-atlas/access_user.tf, modules/mongodb-atlas/alerts.tf, modules/mongodb-atlas/auditing.tf, modules/mongodb-atlas/backup.tf, modules/mongodb-atlas/cluster.tf, modules/mongodb-atlas/network.tf, modules/mongodb-atlas/project.tf, modules/mongodb-atlas/users.tf, modules/mongodb-atlas/variables.tf
##WHY?
New features are added in our MongoDB setups by hand. We need all this infrastructure have configured in Terraform. So this module has to be changed.
##HOW?
We check all created resources and add them in Terraform.
=> Fixed some parts in module.

modules/cloudfront-ssl-hsts/README.md
This case is missing in README file. I've added an example about this case to make it understandable how to create more than one origin.
=> DMVP-404 Added an example how to create 2 origins.

modules/s3/README.md, modules/s3/locals.tf, modules/s3/main.tf, modules/s3/outputs.tf, modules/s3/variables.tf, modules/s3/versions.tf
DMVP-559 have module to create s3 bucket and iam user with full access to list/read/put/delete objects in it
=> DMVP-559 have module to create s3 bucket and iam user with full access to list/read/put/delete objects in it

modules/complete-eks-cluster/main.tf, modules/ingress/variables.tf
When using these 2 modules I encountered problems connected to ingress default values and fluent-bit's region which is passed by a variable.
Added default values for them.
=> Changes in ingress and eks modules

modules/metrics-server/main.tf, modules/metrics-server/values.yaml
=> DMVP-793 upgrade metric server helm chart version as old one was deprecated/removed

modules/ingress/README.md, modules/ingress/data.tf, modules/ingress/examples/k8s/README.md, modules/ingress/examples/k8s/ingress.yaml, modules/ingress/examples/k8s/main.tf, modules/ingress/examples/r53/README.md, modules/ingress/examples/r53/main.tf, modules/ingress/main.tf, modules/ingress/output.tf, modules/ingress/variables.tf
This module has to create a k8s ingress resource which will create an alb in AWS but somehow the current setup doesn’t support this functionality anymore.
Refactored the module.
=> DMVP-1145: Refactored Ingress module

.github/workflows/checkov.yaml, .github/workflows/infracost.yaml, .github/workflows/pre-commit.yaml, .github/workflows/semantic.yaml, .github/workflows/terraform-test.yaml, .github/workflows/tflint.yaml, .github/workflows/tfsec.yaml
https://tutorbot.atlassian.net/browse/DMVP-1324  Add piplines
=> feat(DMVP-1324): add all piplines to aws modules repo

.gitignore, modules/cloudfront-ssl-hsts/ssl-certificate.tf
Change variable name and also change module version
=> DMVP-1338: Modified variable name from zone to zones

modules/cloudfront-ssl-hsts/README.md, modules/cloudfront-ssl-hsts/ssl-certificate.tf, modules/rabbitmq/README.md, modules/rabbitmq/security-group.tf, modules/rabbitmq/tests/README.md, modules/rabbitmq/tests/main.tf, modules/rabbitmq/variables.tf
=> DMVP-1382: RabbitMQ refactoring

modules/rabbitmq/README.md, modules/rabbitmq/tests/README.md, modules/rabbitmq/tests/main.tf
=> DMVP-1382: Docs

modules/cloudwatch-alarm-notify/README.md, modules/cloudwatch-alarm-notify/main.tf
Introducing some defaults for RDS alerts
=> feat(cloudwatch-alarm-notify) introduce alarm defaults for RDS

githooks/commit-msg, modules/cloudtrail/README.md, modules/cloudtrail/cloudwatch.tf, modules/cloudtrail/main.tf, modules/cloudtrail/role.tf, modules/cloudtrail/variables.tf
1. Enabled sending logs from CloudTrail to CloudWatch optionally
2. Added optionally creation of a Log Group for the logs.
=> DMVP-1390: Refactored CloudTrail module

modules/cloudtrail/README.md, modules/cloudtrail/main.tf, modules/cloudtrail/tests/all-events-enabled/0-setup.tf, modules/cloudtrail/tests/all-events-enabled/1-example.tf, modules/cloudtrail/tests/all-events-enabled/2-assert.tf, modules/cloudtrail/variables.tf
We did manage only `Management events`. Added `insight_selector` block.
=> docs(DMVP-1390): Edited README.

modules/alb-logs-to-s3-to-cloudwatch/README.md, modules/alb-logs-to-s3-to-cloudwatch/bucket.tf, modules/alb-logs-to-s3-to-cloudwatch/logs-to-cloudwatch.tf, modules/alb-logs-to-s3-to-cloudwatch/variables.tf, modules/ingress/README.md, modules/ingress/alb-logs-cloudwatch.tf, modules/ingress/main.tf, modules/ingress/tests/enable_s3_logs/0-setup.tf, modules/ingress/tests/enable_s3_logs/1-example.tf, modules/ingress/tests/enable_s3_logs/2-assert.tf, modules/ingress/tests/enable_s3_logs/README.md, modules/ingress/variables.tf
Enable access logs on ALB to s3
=> fix(DMVP-4430): Add s3 logs for ALB
